version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.28
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      # override my.cnf to change character set utf8
      - ./db/config/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: "yata"
      MYSQL_USER: "team16"
      MYSQL_PASSWORD: "team16"
      MYSQL_ROOT_PASSWORD: "team16-su"

  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - "6379:6379"
    restart: always

networks:
  dev:
    driver: bridge