# Generated by Django 2.1.14 on 2019-11-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpoolRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='IDLE', max_length=255)),
                ('from_location', models.CharField(default='', max_length=255)),
                ('to_location', models.CharField(default='', max_length=255)),
                ('minimum_passenger', models.CharField(default='', max_length=15)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Rider')),
            ],
        ),
    ]
