# Generated by Django 2.1.14 on 2019-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(default='', max_length=255)),
                ('to_location', models.CharField(default='', max_length=255)),
                ('cost', models.IntegerField(default=0)),
                ('departure', models.BooleanField(default=False)),
            ],
        ),
    ]
