# Generated by Django 2.1.14 on 2019-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rider_id_list',
            field=models.CharField(default='', max_length=255),
        ),
    ]
