# Generated by Django 2.1.14 on 2019-11-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_rider_id_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='rider_id_list',
        ),
    ]
