# Generated by Django 2.1.14 on 2019-11-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_driver_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_of_group', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(default='IDLE', max_length=255),
        ),
    ]
