# Generated by Django 2.1.14 on 2019-11-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191107_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='status',
            field=models.CharField(default='IDLE', max_length=255),
        ),
    ]
