# Generated by Django 2.1.14 on 2019-12-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191127_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_of_group', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.Group'),
        ),
    ]
