# Generated by Django 2.1.14 on 2019-12-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191201_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.Group'),
        ),
    ]
