apiVersion: apps/v1
kind: Deployment
metadata:
  name: carpool-request-service
  labels:
    service: carpool-request
spec:
  replicas: 1
  selector:
    matchLabels:
      service: carpool-request
  template:
    metadata:
      labels:
        service: carpool-request
    spec:
      containers:
        - name: carpool-request
          image: swpp2019team16/carpool-request-service:latest
          command:
            - "/bin/sh"
            - "-c"
            - "python manage.py migrate --settings=carpool_request_service.settings.production && python manage.py runservice --settings=carpool_request_service.settings.production"
          imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: carpool-request-service
  labels:
    service: carpool-request
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    service: carpool-request