apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
  labels:
    service: group
spec:
  replicas: 1
  selector:
    matchLabels:
      service: group
  template:
    metadata:
      labels:
        service: group
    spec:
      containers:
        - name: group
          image: swpp2019team16/group-service:latest
          command:
            - "/bin/sh"
            - "-c"
            - "python manage.py migrate --settings=group_service.settings.production && python manage.py runservice --settings=group_service.settings.production"
          imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: group-service
  labels:
    service: group
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    service: group