apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    service: user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
        - name: user
          image: swpp2019team16/user-service:latest
          command:
            - "/bin/sh"
            - "-c"
            - "python manage.py migrate --settings=user_service.settings.production && python manage.py runservice --settings=user_service.settings.production"
          imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    service: user
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    service: user